# run KLMC in batch mode

# sets some default verbose
/control/verbose 1
/run/verbose 1
/tracking/verbose 0

/tracking/storeTrajectory 0

/run/initialize
/gun/particle gamma

# -------------------- 100 MeV RUN --------------------
# /gun/energy 100 MeV
#
# /RunAction/FileName SAC_100MeV_n10
#
# /RunAction/GammaPerHitEDep 0.15 MeV
# /RunAction/PositronPerHitEDep 1.5 MeV
# /RunAction/ElectronPerHitEDep 1.5 MeV
# /RunAction/ProtonPerHitEDep 2.0 MeV
# /RunAction/NeutronPerHitEDep 2.0 MeV
# /RunAction/PionPlusPerHitEDep 2.0 MeV
# /RunAction/PionMinusPerHitEDep 2.0 MeV
# /RunAction/PionZeroPerHitEDep 2.0 MeV
# /RunAction/MuonPlusPerHitEDep 2.0 MeV
# /RunAction/MuonMinusPerHitEDep 2.0 MeV
# /RunAction/OptPhotPerHitEDep 5.0 eV
#
# /RunAction/GammaPerHitTrLen 1.8 cm
# /RunAction/PositronPerHitTrLen 0.8 cm
# /RunAction/ElectronPerHitTrLen 0.8 cm
# /RunAction/ProtonPerHitTrLen 2.0 cm
# /RunAction/NeutronPerHitTrLen 2.0 cm
# /RunAction/PionPlusPerHitTrLen 2.0 cm
# /RunAction/PionMinusPerHitTrLen 2.0 cm
# /RunAction/PionZeroPerHitTrLen 2.0 cm
# /RunAction/MuonPlusPerHitTrLen 2.0 cm
# /RunAction/MuonMinusPerHitTrLen 2.0 cm
# /RunAction/OptPhotPerHitTrLen 0.8 cm
#
# /RunAction/GammaPerEventMultMin 0
# /RunAction/GammaPerEventMultMax 100
# /RunAction/PositronPerEventMultMin 0
# /RunAction/PositronPerEventMultMax 20
# /RunAction/ElectronPerEventMultMin 0
# /RunAction/ElectronPerEventMultMax 200
# /RunAction/ProtonPerEventMultMin 0
# /RunAction/ProtonPerEventMultMax 10
# /RunAction/NeutronPerEventMultMin 0
# /RunAction/NeutronPerEventMultMax 10
# /RunAction/PionPlusPerEventMultMin 0
# /RunAction/PionPlusPerEventMultMax 10
# /RunAction/PionMinusPerEventMultMin 0
# /RunAction/PionMinusPerEventMultMax 10
# /RunAction/PionZeroPerEventMultMin 0
# /RunAction/PionZeroPerEventMultMax 10
# /RunAction/MuonPlusPerEventMultMin 0
# /RunAction/MuonPlusPerEventMultMax 10
# /RunAction/MuonMinusPerEventMultMin 0
# /RunAction/MuonMinusPerEventMultMax 10
# /RunAction/OptPhotPerEventMultMin 7000
# /RunAction/OptPhotPerEventMultMax 10000
#
# /RunAction/GammaPerEventEDep 5.0 MeV
# /RunAction/PositronPerEventEDep 100.0 MeV
# /RunAction/ElectronPerEventEDep 100.0 MeV
# /RunAction/ProtonPerEventEDep 5.0 MeV
# /RunAction/NeutronPerEventEDep 5.0 MeV
# /RunAction/PionPlusPerEventEDep 5.0 MeV
# /RunAction/PionMinusPerEventEDep 5.0 MeV
# /RunAction/PionZeroPerEventEDep 5.0 MeV
# /RunAction/MuonPlusPerEventEDep 5.0 MeV
# /RunAction/MuonMinusPerEventEDep 5.0 MeV
# /RunAction/OptPhotPerEventEDep 0.05 MeV
#
# /RunAction/GammaPerEventInitE 50.0 MeV
# /RunAction/PositronPerEventInitE 50.0 MeV
# /RunAction/ElectronPerEventInitE 50.0 MeV
# /RunAction/ProtonPerEventInitE 10.0 MeV
# /RunAction/NeutronPerEventInitE 10.0 MeV
# /RunAction/PionPlusPerEventInitE 10.0 MeV
# /RunAction/PionMinusPerEventInitE 10.0 MeV
# /RunAction/PionZeroPerEventInitE 10.0 MeV
# /RunAction/MuonPlusPerEventInitE 10.0 MeV
# /RunAction/MuonMinusPerEventInitE 10.0 MeV
# /RunAction/OptPhotPerEventInitE 5.0 eV
#
# /RunAction/PerEventEDepMin 50.0 MeV
# /RunAction/PerEventEDepMax 100.0 MeV
# /RunAction/PerEventUntrackedE 50.0 keV
#
# /run/beamOn 10

# -------------------- 200 MeV RUN --------------------
/gun/energy 200 MeV

/RunAction/FileName SAC_200MeV_n10

/RunAction/GammaPerHitEDep 0.15 MeV
/RunAction/PositronPerHitEDep 1.5 MeV
/RunAction/ElectronPerHitEDep 1.5 MeV
/RunAction/ProtonPerHitEDep 2.0 MeV
/RunAction/NeutronPerHitEDep 2.0 MeV
/RunAction/PionPlusPerHitEDep 2.0 MeV
/RunAction/PionMinusPerHitEDep 2.0 MeV
/RunAction/PionZeroPerHitEDep 2.0 MeV
/RunAction/MuonPlusPerHitEDep 2.0 MeV
/RunAction/MuonMinusPerHitEDep 2.0 MeV
/RunAction/OptPhotPerHitEDep 5.0 eV

/RunAction/GammaPerHitTrLen 1.8 cm
/RunAction/PositronPerHitTrLen 0.8 cm
/RunAction/ElectronPerHitTrLen 0.8 cm
/RunAction/ProtonPerHitTrLen 2.0 cm
/RunAction/NeutronPerHitTrLen 2.0 cm
/RunAction/PionPlusPerHitTrLen 2.0 cm
/RunAction/PionMinusPerHitTrLen 2.0 cm
/RunAction/PionZeroPerHitTrLen 2.0 cm
/RunAction/MuonPlusPerHitTrLen 2.0 cm
/RunAction/MuonMinusPerHitTrLen 2.0 cm
/RunAction/OptPhotPerHitTrLen 0.8 cm

/RunAction/GammaPerEventMultMin 0
/RunAction/GammaPerEventMultMax 100
/RunAction/PositronPerEventMultMin 0
/RunAction/PositronPerEventMultMax 20
/RunAction/ElectronPerEventMultMin 0
/RunAction/ElectronPerEventMultMax 200
/RunAction/ProtonPerEventMultMin 0
/RunAction/ProtonPerEventMultMax 10
/RunAction/NeutronPerEventMultMin 0
/RunAction/NeutronPerEventMultMax 10
/RunAction/PionPlusPerEventMultMin 0
/RunAction/PionPlusPerEventMultMax 10
/RunAction/PionMinusPerEventMultMin 0
/RunAction/PionMinusPerEventMultMax 10
/RunAction/PionZeroPerEventMultMin 0
/RunAction/PionZeroPerEventMultMax 10
/RunAction/MuonPlusPerEventMultMin 0
/RunAction/MuonPlusPerEventMultMax 10
/RunAction/MuonMinusPerEventMultMin 0
/RunAction/MuonMinusPerEventMultMax 10
/RunAction/OptPhotPerEventMultMin 7000
/RunAction/OptPhotPerEventMultMax 20000

/RunAction/GammaPerEventEDep 5.0 MeV
/RunAction/PositronPerEventEDep 100.0 MeV
/RunAction/ElectronPerEventEDep 100.0 MeV
/RunAction/ProtonPerEventEDep 5.0 MeV
/RunAction/NeutronPerEventEDep 5.0 MeV
/RunAction/PionPlusPerEventEDep 5.0 MeV
/RunAction/PionMinusPerEventEDep 5.0 MeV
/RunAction/PionZeroPerEventEDep 5.0 MeV
/RunAction/MuonPlusPerEventEDep 5.0 MeV
/RunAction/MuonMinusPerEventEDep 5.0 MeV
/RunAction/OptPhotPerEventEDep 0.05 MeV

/RunAction/GammaPerEventInitE 50.0 MeV
/RunAction/PositronPerEventInitE 50.0 MeV
/RunAction/ElectronPerEventInitE 50.0 MeV
/RunAction/ProtonPerEventInitE 10.0 MeV
/RunAction/NeutronPerEventInitE 10.0 MeV
/RunAction/PionPlusPerEventInitE 10.0 MeV
/RunAction/PionMinusPerEventInitE 10.0 MeV
/RunAction/PionZeroPerEventInitE 10.0 MeV
/RunAction/MuonPlusPerEventInitE 10.0 MeV
/RunAction/MuonMinusPerEventInitE 10.0 MeV
/RunAction/OptPhotPerEventInitE 5.0 eV

/RunAction/PerEventEDepMin 125.0 MeV
/RunAction/PerEventEDepMax 200.0 MeV
/RunAction/PerEventUntrackedE 50.0 keV

/run/beamOn 10

# -------------------- 500 MeV RUN --------------------
# /gun/energy 500 MeV
# /RunAction/FileName SAC_500MeV_n1
# /run/beamOn 1

# -------------------- 1 GeV RUN --------------------
# /gun/energy 1 GeV
# /RunAction/FileName SAC_1GeV_n1
# /run/beamOn 1

# -------------------- 2 GeV RUN --------------------
# /gun/energy 2 GeV
# /RunAction/FileName SAC_2GeV_n1
# /run/beamOn 1

# -------------------- 5 GeV RUN --------------------
# /gun/energy 5 GeV
# /RunAction/FileName SAC_5GeV_n1
# /run/beamOn 1

# -------------------- 10 GeV RUN --------------------
# /gun/energy 10 GeV
# /RunAction/FileName SAC_10GeV_n1
# /run/beamOn 1

# -------------------- 20 GeV RUN --------------------
# /gun/energy 20 GeV
# /RunAction/FileName SAC_20GeV_n1
# /run/beamOn 1

# -------------------- 50 GeV RUN --------------------
# /gun/energy 50 GeV
# /RunAction/FileName SAC_50GeV_n1
# /run/beamOn 1

# -------------------- 100 GeV RUN --------------------
# /gun/energy 100 GeV
# /RunAction/FileName SAC_100GeV_n1
# /run/beamOn 1
