/control/verbose 1
/run/verbose 1
/tracking/verbose 0

# 0 -- don't store particle tracks, runs faster
# 1 -- stored particle tracks are drawn in viewer, runs very slow
/tracking/storeTrajectory 0

/run/initialize
/gun/particle neutron

/gun/energy 100 GeV

/Detector/SAC/IncidentE 100.0 GeV

/RunAction/FileName SAC_100GeV_n1_neutron

/RunAction/GammaPerEventInitE 100.0 GeV
/RunAction/PositronPerEventInitE 100.0 GeV
/RunAction/ElectronPerEventInitE 100.0 GeV
/RunAction/ProtonPerEventInitE 100.0 GeV
/RunAction/NeutronPerEventInitE 100.0 GeV
/RunAction/OptPhotPerEventInitE 5.0 eV

/RunAction/PerEventEDep 100.0 GeV
/RunAction/PerEventUntrackedE 100.0 GeV

/run/beamOn 1
