/control/verbose 1
/run/verbose 1
/tracking/verbose 0

# 0 -- don't store particle tracks, runs faster
# 1 -- stored particle tracks are drawn in viewer, runs very slow
/tracking/storeTrajectory 0

/run/initialize
/gun/particle gamma

/gun/energy 100 MeV

/Detector/SAC/IncidentE 100.0 MeV

/RunAction/FileName SAC_100MeV_n1_gamma

/RunAction/GammaPerEventInitE 100.0 MeV
/RunAction/PositronPerEventInitE 100.0 MeV
/RunAction/ElectronPerEventInitE 100.0 MeV
/RunAction/ProtonPerEventInitE 100.0 MeV
/RunAction/NeutronPerEventInitE 100.0 MeV
/RunAction/OptPhotPerEventInitE 5.0 eV

/RunAction/PerEventEDep 100.0 MeV
/RunAction/PerEventUntrackedE 100.0 MeV

/run/beamOn 1
