/control/verbose 1
/run/verbose 1
/tracking/verbose 0

# 0 -- don't store particle tracks, runs faster
# 1 -- stored particle tracks are drawn in viewer, runs very slow
/tracking/storeTrajectory 0

/run/initialize
/gun/particle neutron

/gun/energy 1 GeV

/RunAction/FileName SAC_1GeV_n20_neutron

/RunAction/GammaPerEventMultMin 150
/RunAction/GammaPerEventMultMax 1000
/RunAction/PositronPerEventMultMin 10
/RunAction/PositronPerEventMultMax 100
/RunAction/ElectronPerEventMultMin 300
/RunAction/ElectronPerEventMultMax 1200
/RunAction/ProtonPerEventMultMin 0
/RunAction/ProtonPerEventMultMax 20
/RunAction/NeutronPerEventMultMin 0
/RunAction/NeutronPerEventMultMax 20
/RunAction/OptPhotPerEventMultMin 22000
/RunAction/OptPhotPerEventMultMax 200000

/RunAction/GammaPerEventEDep 50.0 MeV
/RunAction/PositronPerEventEDep 500.0 MeV
/RunAction/ElectronPerEventEDep 1.0 GeV
/RunAction/ProtonPerEventEDep 20.0 MeV
/RunAction/NeutronPerEventEDep 5.0 MeV
/RunAction/OptPhotPerEventEDep 0.5 MeV

/RunAction/GammaPerEventInitE 1.1 GeV
/RunAction/PositronPerEventInitE 1.1 GeV
/RunAction/ElectronPerEventInitE 1.1 GeV
/RunAction/ProtonPerEventInitE 1.1 GeV
/RunAction/NeutronPerEventInitE 11.0 GeV
/RunAction/OptPhotPerEventInitE 5.0 eV

/RunAction/PerEventEDepMin 0.3 GeV
/RunAction/PerEventEDepMax 1.1 GeV
/RunAction/PerEventUntrackedE 10.0 MeV

/run/beamOn 20
