/control/verbose 1
/run/verbose 1
/tracking/verbose 0

# 0 -- don't store particle tracks, runs faster
# 1 -- stored particle tracks are drawn in viewer, runs very slow
/tracking/storeTrajectory 0

/run/initialize
/gun/particle gamma

/gun/energy 200 MeV

/Detector/SAC/IncidentE 200.0 MeV

/RunAction/FileName SAC_200MeV_n1_gamma

/RunAction/GammaPerEventInitE 200.0 MeV
/RunAction/PositronPerEventInitE 200.0 MeV
/RunAction/ElectronPerEventInitE 200.0 MeV
/RunAction/ProtonPerEventInitE 200.0 MeV
/RunAction/NeutronPerEventInitE 200.0 MeV
/RunAction/OptPhotPerEventInitE 5.0 eV

/RunAction/PerEventEDep 200.0 MeV
/RunAction/PerEventUntrackedE 200.0 MeV

/run/beamOn 1
