/control/verbose 1
/run/verbose 1
/tracking/verbose 0

# 0 -- don't store particle tracks, runs faster
# 1 -- stored particle tracks are drawn in viewer, runs very slow
/tracking/storeTrajectory 0

/run/initialize
/gun/particle gamma

/gun/energy 20 GeV

/Detector/SAC/IncidentE 20.0 GeV

/RunAction/FileName SAC_20GeV_n1_gamma

/RunAction/GammaPerEventInitE 20.0 GeV
/RunAction/PositronPerEventInitE 20.0 GeV
/RunAction/ElectronPerEventInitE 20.0 GeV
/RunAction/ProtonPerEventInitE 20.0 GeV
/RunAction/NeutronPerEventInitE 20.0 GeV
/RunAction/OptPhotPerEventInitE 5.0 eV

/RunAction/PerEventEDep 20.0 GeV
/RunAction/PerEventUntrackedE 20.0 GeV

/run/beamOn 1
