/control/verbose 1
/run/verbose 1
/tracking/verbose 0

# 0 -- don't store particle tracks, runs faster
# 1 -- stored particle tracks are drawn in viewer, runs very slow
/tracking/storeTrajectory 0

/run/initialize
/gun/particle neutron

/gun/energy 500 MeV

/Detector/SAC/IncidentE 500.0 MeV

/RunAction/FileName SAC_500MeV_n1_neutron

/RunAction/GammaPerEventInitE 500.0 MeV
/RunAction/PositronPerEventInitE 500.0 MeV
/RunAction/ElectronPerEventInitE 500.0 MeV
/RunAction/ProtonPerEventInitE 500.0 MeV
/RunAction/NeutronPerEventInitE 500.0 MeV
/RunAction/OptPhotPerEventInitE 5.0 eV

/RunAction/PerEventEDep 500.0 MeV
/RunAction/PerEventUntrackedE 500.0 MeV

/run/beamOn 1
