/control/verbose 1
/run/verbose 1
/tracking/verbose 0

# 0 -- don't store particle tracks, runs faster
# 1 -- stored particle tracks are drawn in viewer, runs very slow
/tracking/storeTrajectory 0

/run/initialize
/gun/particle neutron

/gun/energy 50 GeV

/RunAction/FileName SAC_50GeV_n2_neutron

/RunAction/GammaPerEventMultMin 15000
/RunAction/GammaPerEventMultMax 30000
/RunAction/PositronPerEventMultMin 1000
/RunAction/PositronPerEventMultMax 3000
/RunAction/ElectronPerEventMultMin 30000
/RunAction/ElectronPerEventMultMax 60000
/RunAction/ProtonPerEventMultMin 0
/RunAction/ProtonPerEventMultMax 50
/RunAction/NeutronPerEventMultMin 0
/RunAction/NeutronPerEventMultMax 50
/RunAction/OptPhotPerEventMultMin 3000000
/RunAction/OptPhotPerEventMultMax 5000000

/RunAction/GammaPerEventEDep 3.0 GeV
/RunAction/PositronPerEventEDep 20.0 GeV
/RunAction/ElectronPerEventEDep 40.0 GeV
/RunAction/ProtonPerEventEDep 50.0 MeV
/RunAction/NeutronPerEventEDep 5.0 MeV
/RunAction/OptPhotPerEventEDep 15.0 MeV

/RunAction/GammaPerEventInitE 51.0 GeV
/RunAction/PositronPerEventInitE 51.0 GeV
/RunAction/ElectronPerEventInitE 51.0 GeV
/RunAction/ProtonPerEventInitE 51.0 GeV
/RunAction/NeutronPerEventInitE 510.0 GeV
/RunAction/OptPhotPerEventInitE 5.0 eV

/RunAction/PerEventEDepMin 25.0 GeV
/RunAction/PerEventEDepMax 50.1 GeV
/RunAction/PerEventUntrackedE 1.0 GeV

/run/beamOn 2
