/control/verbose 1
/run/verbose 1
/tracking/verbose 0

# 0 -- don't store particle tracks, runs faster
# 1 -- stored particle tracks are drawn in viewer, runs very slow
/tracking/storeTrajectory 0

/run/initialize
/gun/particle neutron

/gun/energy 5 GeV

/Detector/SAC/IncidentE 5.0 GeV

/RunAction/FileName SAC_5GeV_n1_neutron

/RunAction/GammaPerEventInitE 5.0 GeV
/RunAction/PositronPerEventInitE 5.0 GeV
/RunAction/ElectronPerEventInitE 5.0 GeV
/RunAction/ProtonPerEventInitE 5.0 GeV
/RunAction/NeutronPerEventInitE 5.0 GeV
/RunAction/OptPhotPerEventInitE 5.0 eV

/RunAction/PerEventEDep 5.0 GeV
/RunAction/PerEventUntrackedE 5.0 GeV

/run/beamOn 1
