# run KLMC in batch mode

# sets some default verbose
/control/verbose 1
/run/verbose 1
/tracking/verbose 0

/tracking/storeTrajectory 0

/run/initialize
/gun/particle gamma

/gun/energy 100 MeV

/RunAction/FileName SAC_100MeV_n1000

/RunAction/GammaPerEventMultMin 0
/RunAction/GammaPerEventMultMax 100
/RunAction/PositronPerEventMultMin 0
/RunAction/PositronPerEventMultMax 20
/RunAction/ElectronPerEventMultMin 0
/RunAction/ElectronPerEventMultMax 200
/RunAction/ProtonPerEventMultMin 0
/RunAction/ProtonPerEventMultMax 10
/RunAction/NeutronPerEventMultMin 0
/RunAction/NeutronPerEventMultMax 10
/RunAction/OptPhotPerEventMultMin 6000
/RunAction/OptPhotPerEventMultMax 10000

/RunAction/GammaPerEventEDep 5.0 MeV
/RunAction/PositronPerEventEDep 100.0 MeV
/RunAction/ElectronPerEventEDep 100.0 MeV
/RunAction/ProtonPerEventEDep 20.0 MeV
/RunAction/NeutronPerEventEDep 5.0 MeV
/RunAction/OptPhotPerEventEDep 0.05 MeV

/RunAction/GammaPerEventInitE 110.0 MeV
/RunAction/PositronPerEventInitE 110.0 MeV
/RunAction/ElectronPerEventInitE 110.0 MeV
/RunAction/ProtonPerEventInitE 110.0 MeV
/RunAction/NeutronPerEventInitE 1100.0 MeV
/RunAction/OptPhotPerEventInitE 5.0 eV

/RunAction/PerEventEDepMin 50.0 MeV
/RunAction/PerEventEDepMax 110.0 MeV
/RunAction/PerEventUntrackedE 0.2 MeV

/run/beamOn 1000
