/control/verbose 1
/run/verbose 1
/tracking/verbose 0

# 0 -- don't store particle tracks, runs faster
# 1 -- stored particle tracks are drawn in viewer, runs very slow
/tracking/storeTrajectory 0

/run/initialize

/PrimaryGeneratorAction/BeamType 0
/PrimaryGeneratorAction/BeamEnergy 100.0 MeV

/HistManager/FileName SAC_0_100MeV_n10

/HistManager/HistToChange h1Mult_PerEvent_all
/HistManager/LowXBound 7000
/HistManager/HighXBound 10000
/HistManager/HistToChange h1Mult_PerEvent_e+
/HistManager/LowXBound 0
/HistManager/HighXBound 40
/HistManager/HistToChange h1Mult_PerEvent_e-
/HistManager/LowXBound 0
/HistManager/HighXBound 400
/HistManager/HistToChange h1Mult_PerEvent_gamma
/HistManager/LowXBound 0
/HistManager/HighXBound 200
/HistManager/HistToChange h1Mult_PerEvent_mu+
/HistManager/LowXBound 0
/HistManager/HighXBound 10
/HistManager/HistToChange h1Mult_PerEvent_mu-
/HistManager/LowXBound 0
/HistManager/HighXBound 10
/HistManager/HistToChange h1Mult_PerEvent_neutron
/HistManager/LowXBound 0
/HistManager/HighXBound 10
/HistManager/HistToChange h1Mult_PerEvent_opticalphoton
/HistManager/LowXBound 7000
/HistManager/HighXBound 10000
/HistManager/HistToChange h1Mult_PerEvent_other
/HistManager/LowXBound 0
/HistManager/HighXBound 40
/HistManager/HistToChange h1Mult_PerEvent_pi+
/HistManager/LowXBound 0
/HistManager/HighXBound 10
/HistManager/HistToChange h1Mult_PerEvent_pi-
/HistManager/LowXBound 0
/HistManager/HighXBound 10
/HistManager/HistToChange h1Mult_PerEvent_pi0
/HistManager/LowXBound 0
/HistManager/HighXBound 10
/HistManager/HistToChange h1Mult_PerEvent_proton
/HistManager/LowXBound 0
/HistManager/HighXBound 10
/HistManager/HistToChange h1Mult_PerEvent_untracked
/HistManager/LowXBound 0
/HistManager/HighXBound 10

/HistManager/HistToChange h1EDep_PerEvent_all
/HistManager/LowXBoundWithUnit 0.0 MeV
/HistManager/HighXBoundWithUnit 100.0 MeV
/HistManager/HistToChange h1EDep_PerEvent_e+
/HistManager/LowXBoundWithUnit 0.0 MeV
/HistManager/HighXBoundWithUnit 100.0 MeV
/HistManager/HistToChange h1EDep_PerEvent_e-
/HistManager/LowXBoundWithUnit 0.0 MeV
/HistManager/HighXBoundWithUnit 100.0 MeV
/HistManager/HistToChange h1EDep_PerEvent_gamma
/HistManager/LowXBoundWithUnit 0.0 MeV
/HistManager/HighXBoundWithUnit 100.0 MeV
/HistManager/HistToChange h1EDep_PerEvent_mu+
/HistManager/LowXBoundWithUnit 0.0 MeV
/HistManager/HighXBoundWithUnit 100.0 MeV
/HistManager/HistToChange h1EDep_PerEvent_mu-
/HistManager/LowXBoundWithUnit 0.0 MeV
/HistManager/HighXBoundWithUnit 100.0 MeV
/HistManager/HistToChange h1EDep_PerEvent_neutron
/HistManager/LowXBoundWithUnit 0.0 MeV
/HistManager/HighXBoundWithUnit 100.0 MeV
/HistManager/HistToChange h1EDep_PerEvent_opticalphoton
/HistManager/LowXBoundWithUnit 0.0 MeV
/HistManager/HighXBoundWithUnit 100.0 MeV
/HistManager/HistToChange h1EDep_PerEvent_other
/HistManager/LowXBoundWithUnit 0.0 MeV
/HistManager/HighXBoundWithUnit 100.0 MeV
/HistManager/HistToChange h1EDep_PerEvent_pi+
/HistManager/LowXBoundWithUnit 0.0 MeV
/HistManager/HighXBoundWithUnit 100.0 MeV
/HistManager/HistToChange h1EDep_PerEvent_pi-
/HistManager/LowXBoundWithUnit 0.0 MeV
/HistManager/HighXBoundWithUnit 100.0 MeV
/HistManager/HistToChange h1EDep_PerEvent_pi0
/HistManager/LowXBoundWithUnit 0.0 MeV
/HistManager/HighXBoundWithUnit 100.0 MeV
/HistManager/HistToChange h1EDep_PerEvent_proton
/HistManager/LowXBoundWithUnit 0.0 MeV
/HistManager/HighXBoundWithUnit 100.0 MeV
/HistManager/HistToChange h1EDep_PerEvent_untracked
/HistManager/LowXBoundWithUnit 0.0 MeV
/HistManager/HighXBoundWithUnit 100.0 MeV

/HistManager/HistToChange h1TrLen_PerHit_all
/HistManager/LowXBoundWithUnit 0.0 cm
/HistManager/HighXBoundWithUnit 202.5 cm
/HistManager/HistToChange h1TrLen_PerHit_e+
/HistManager/LowXBoundWithUnit 0.0 cm
/HistManager/HighXBoundWithUnit 202.5 cm
/HistManager/HistToChange h1TrLen_PerHit_e-
/HistManager/LowXBoundWithUnit 0.0 cm
/HistManager/HighXBoundWithUnit 202.5 cm
/HistManager/HistToChange h1TrLen_PerHit_gamma
/HistManager/LowXBoundWithUnit 0.0 cm
/HistManager/HighXBoundWithUnit 202.5 cm
/HistManager/HistToChange h1TrLen_PerHit_mu+
/HistManager/LowXBoundWithUnit 0.0 cm
/HistManager/HighXBoundWithUnit 202.5 cm
/HistManager/HistToChange h1TrLen_PerHit_mu-
/HistManager/LowXBoundWithUnit 0.0 cm
/HistManager/HighXBoundWithUnit 202.5 cm
/HistManager/HistToChange h1TrLen_PerHit_neutron
/HistManager/LowXBoundWithUnit 0.0 cm
/HistManager/HighXBoundWithUnit 202.5 cm
/HistManager/HistToChange h1TrLen_PerHit_opticalphoton
/HistManager/LowXBoundWithUnit 0.0 cm
/HistManager/HighXBoundWithUnit 202.5 cm
/HistManager/HistToChange h1TrLen_PerHit_other
/HistManager/LowXBoundWithUnit 0.0 cm
/HistManager/HighXBoundWithUnit 202.5 cm
/HistManager/HistToChange h1TrLen_PerHit_pi+
/HistManager/LowXBoundWithUnit 0.0 cm
/HistManager/HighXBoundWithUnit 202.5 cm
/HistManager/HistToChange h1TrLen_PerHit_pi-
/HistManager/LowXBoundWithUnit 0.0 cm
/HistManager/HighXBoundWithUnit 202.5 cm
/HistManager/HistToChange h1TrLen_PerHit_pi0
/HistManager/LowXBoundWithUnit 0.0 cm
/HistManager/HighXBoundWithUnit 202.5 cm
/HistManager/HistToChange h1TrLen_PerHit_proton
/HistManager/LowXBoundWithUnit 0.0 cm
/HistManager/HighXBoundWithUnit 202.5 cm
/HistManager/HistToChange h1TrLen_PerHit_untracked
/HistManager/LowXBoundWithUnit 0.0 cm
/HistManager/HighXBoundWithUnit 202.5 cm

/HistManager/HistToChange h1MultLow_PerEvent_all
/HistManager/LowXBound 7000
/HistManager/HighXBound 8500
/HistManager/HistToChange h1MultLow_PerEvent_e+
/HistManager/LowXBound 0
/HistManager/HighXBound 20
/HistManager/HistToChange h1MultLow_PerEvent_e-
/HistManager/LowXBound 0
/HistManager/HighXBound 200
/HistManager/HistToChange h1MultLow_PerEvent_gamma
/HistManager/LowXBound 0
/HistManager/HighXBound 100
/HistManager/HistToChange h1MultLow_PerEvent_mu+
/HistManager/LowXBound 0
/HistManager/HighXBound 5
/HistManager/HistToChange h1MultLow_PerEvent_mu-
/HistManager/LowXBound 0
/HistManager/HighXBound 5
/HistManager/HistToChange h1MultLow_PerEvent_neutron
/HistManager/LowXBound 0
/HistManager/HighXBound 5
/HistManager/HistToChange h1MultLow_PerEvent_opticalphoton
/HistManager/LowXBound 7000
/HistManager/HighXBound 8500
/HistManager/HistToChange h1MultLow_PerEvent_other
/HistManager/LowXBound 0
/HistManager/HighXBound 20
/HistManager/HistToChange h1MultLow_PerEvent_pi+
/HistManager/LowXBound 0
/HistManager/HighXBound 5
/HistManager/HistToChange h1MultLow_PerEvent_pi-
/HistManager/LowXBound 0
/HistManager/HighXBound 5
/HistManager/HistToChange h1MultLow_PerEvent_pi0
/HistManager/LowXBound 0
/HistManager/HighXBound 5
/HistManager/HistToChange h1MultLow_PerEvent_proton
/HistManager/LowXBound 0
/HistManager/HighXBound 5
/HistManager/HistToChange h1MultLow_PerEvent_untracked
/HistManager/LowXBound 0
/HistManager/HighXBound 5

/run/beamOn 10
