# Visualize KLMC_SAC

# -------------------------------------------- #

# Set some default verbose
/control/verbose 1
/run/verbose 1
/tracking/verbose 0

# Detector settings
# /Detector/SAC/CrystalSize 2.0 cm
# /Detector/SAC/CrystalLength 3.75 cm
# /Detector/SAC/CrystalCoating 100.0 um
# /Detector/SAC/CellGap 50.0 um
# /Detector/SAC/LayerGap 2.0 cm
# /Detector/SAC/NRows 10
# /Detector/SAC/NCols 10
# /Detector/SAC/NLayers 4
# /Detector/SAC/EnablePMT 0
# /Detector/SAC/EnableSiPM 0
# /Detector/SAC/VerboseLevel 0
# /Detector/SAC/FrontFaceZ 300.0 cm
# /Detector/UpdateGeometry

# Create detectors and initialize run
/run/initialize

# Use this open statement to create an OpenGL view (comment out below):
/vis/open OGL 600x600-0+0

# Use this to see ASCIITree (comment out above):
# /vis/open ATree
# /vis/ASCIITree/verbose 14

# Disable auto refresh and quieten vis messages whilst scene and trajectories
# are established:
/vis/viewer/set/autoRefresh false
/vis/verbose errors

# Draw geometry:
/vis/drawVolume
# /geometry/test/grid_test true

# Choose viewpoint
# /vis/viewer/set/viewpointVector 0.0 10.0 0.0
# Side view
/vis/viewer/set/viewpointThetaPhi -90.0 0.0 deg
# Top view
# /vis/viewer/set/viewpointThetaPhi 90.0 90.0 deg
# Front view
# /vis/viewer/set/viewpointThetaPhi 0.0 0.0 deg
# Back view
# /vis/viewer/set/viewpointThetaPhi 180.0 0.0 deg

# Specify zoom value:
# /vis/viewer/zoom 2

# Specify style (surface or wireframe):
/vis/viewer/set/style wireframe
# /vis/viewer/set/style surface

# Draw coordinate axes:
# /vis/scene/add/axes 0 0 0 1 m

# Decorations
/vis/set/textColour green
/vis/set/textLayout right
/vis/scene/add/text2D 0.9 -0.9 24 ! ! KLEVER SAC
/vis/set/textLayout # revert to normal (left adjusted) layout
/vis/set/textColour # revert to default text colour (blue)
/vis/scene/add/eventID # drawn at end of event
/vis/scene/add/date # date stamp

# Draw smooth trajectories at end of event, showing trajectory points as markers
# 2 pixels wide:
/vis/scene/add/trajectories smooth
# /vis/modeling/trajectories/create/drawByCharge
# /vis/modeling/trajectories/drawByCharge-0/default/setDrawStepPts true
# /vis/modeling/trajectories/drawByCharge-0/default/setStepPtsSize 1

# If too many tracks cause core dump => /tracking/storeTrajectory 0
/tracking/storeTrajectory 1

# Draw hits at end of event:
/vis/scene/add/hits

# To draw only certain particles:
# /vis/filtering/trajectories/create/particleFilter
# /vis/filtering/trajectories/particleFilter-0/add gamma
# /vis/filtering/trajectories/particleFilter-0/add positron
# /vis/filtering/trajectories/particleFilter-0/add electron
# /vis/filtering/trajectories/particleFilter-0/add proton
# /vis/filtering/trajectories/particleFilter-0/add neutron
# /vis/filtering/trajectories/particleFilter-0/add opticalphoton

# To invert the above, drawing all particles except certain ones, keep the above
# lines but also add:
# /vis/filtering/trajectories/particleFilter-0/invert true

# To select colour by particle ID:
/vis/modeling/trajectories/create/drawByParticleID
/vis/modeling/trajectories/drawByParticleID-0/set gamma white
/vis/modeling/trajectories/drawByParticleID-0/set positron green
/vis/modeling/trajectories/drawByParticleID-0/set electron blue
/vis/modeling/trajectories/drawByParticleID-0/set proton yellow
/vis/modeling/trajectories/drawByParticleID-0/set neutron magenta
/vis/modeling/trajectories/drawByParticleID-0/set opticalphoton cyan

# To superimpose all of the events from a given run:
# /vis/scene/endOfEventAction accumulate

# Re-establish auto refreshing and verbosity:
/vis/viewer/set/autoRefresh true
/vis/verbose warnings

# Fix problem in visualizing some circular parts
# /vis/viewer/set/lineSegmentsPerCircle 50

/vis/scene/endOfEventAction accumulate 10

/vis/viewer/flush

# Only show tracks with p > 1MeV
# /vis/filtering/trajectories/create/attributeFilter
# /vis/filtering/trajectories/attributeFilter-0/setAttribute IMag
# /vis/filtering/trajectories/attributeFilter-0/addInterval 1.0 MeV 100000.0 MeV

# /run/beamOn 1
